Category.create(name:'メンズ')
Category.create(name:'レディース')
Category.create(name:'キッズ')
Idea.create(body:'idea1', category_id:'1')
Idea.create(body:'idea2', category_id:'2')
Idea.create(body:'idea3', category_id:'3')
Idea.create(body:'idea4', category_id:'1')
Idea.create(body:'idea5', category_id:'2')